version: '3.7'

services:
  mongo:
    image: mongo:5.0
    container_name: geofence_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - volume_geofence_mongo:/data/db
    ports:
      - 27017:27017
    networks:
      default:

volumes:
  volume_geofence_mongo:

networks:
  default:
